# continuous_spread_map_h7n9.R
# Author: <Your Name>
# Date: 2024-05-**
#
# Description ---------------------------------------------------------------
# This script reproduces the continuous spatial diffusion map for Influenza
# A(H7N9) under a Brownian motion model. It relies on posterior trees
# generated by BEAST and the seraphim package to visualise HPD regions and
# diffusion trajectories.
#
# Input files
#  * H7N9_mafft.trees        – posterior tree set (BEAST output)
#  * H7N9_mcc.tree           – maximum clade credibility tree
#  * global_raster.asc       – world template raster (ASCII grid)
#
# Output
#  * Static figure rendered to current working directory (PNG/PDF)
#
# Usage ---------------------------------------------------------------------
#   setwd("<project-root>/src/r/continuous/H7N9")
#   source("continuous_spread_map_h7n9.R")
# ---------------------------------------------------------------------------

## Load libraries -----------------------------------------------------------
# NOTE: It is assumed that all required packages have been installed via the
# installation instructions in the repository README.

library(seraphim)
library(diagram)
library(raster)
library(rnaturalearth)
library(rnaturalearthdata)
# Add any other libraries that are required by downstream functions

## Parameters ---------------------------------------------------------------
local_trees_dir      <- "Tree_extractions"
burnin_fraction      <- 0        # adjust if necessary
sample_size          <- 1000     # number of trees to sample from posterior
most_recent_datum    <- 2024.39  # decimal year of most recent sample
coord_attr           <- "location"

## 1. Extract spatio-temporal information from posterior trees --------------
all_trees <- scan(file = "H7N9_mafft.trees", what = "", sep = "\n", quiet = TRUE)

seraphim::treeExtractions(
  directory             = local_trees_dir,
  treeSample            = all_trees,
  burnIn                = burnin_fraction,
  randomSampling        = FALSE,
  nberOfTreesToSample   = sample_size,
  mostRecentSamplingDatum = most_recent_datum,
  coordinateAttributeName = coord_attr
)

## 2. Extract spatio-temporal information from the MCC tree -----------------
source("mccExtractions2.R")

mcc_tree <- seraphim::readAnnotatedNexus("H7N9_mcc.tree")
mcc_tab  <- mccExtractions(mcc_tree, most_recent_datum)

## 3. Estimate the 95% HPD region for each time slice -----------------------
prob      <- 0.95
precision <- 0.025
start_datum <- min(mcc_tab[, "startYear"])

polygons <- suppressWarnings(
  spreadGraphic2(
    treeExtractionsDirectory = local_trees_dir,
    nberOfExtractionFiles    = sample_size,
    prob                     = prob,
    startDatum               = start_datum,
    precision                = precision
  )
)

## 4. Define colour scales --------------------------------------------------
colour_scale <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(11, "RdYlGn"))(141)[21:121]
colour_scale <- rev(colour_scale)  # oldest dates in grey, recent in red

min_year <- min(mcc_tab[, "startYear"])
max_year <- max(mcc_tab[, "endYear"])

end_year_indices <- ((mcc_tab[, "endYear"] - min_year) / (max_year - min_year)) * 100 + 1
end_year_colours <- colour_scale[round(end_year_indices)]

## 5. Co-plot HPD regions and MCC tree -------------------------------------

template_raster <- raster::raster("global_raster.asc")
world_sf        <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

graphics::dev.new(width = 10, height = 6.3)
par(mar = c(0,0,0,0), oma = c(1.2,3.5,1,0), mgp = c(0,0.4,0), lwd = 0.2, bty = "o")

# Plot base raster and country borders
plot(template_raster, col = "white", box = FALSE, axes = FALSE, colNA = "grey90", legend = FALSE)
plot(world_sf, add = TRUE, col = "white", border = "gray20", lwd = 0.1)

# Plot polygons (HPD regions)
polygon_cols <- sapply(names(polygons), function(date_str) {
  date_val <- as.numeric(date_str)
  idx      <- round(((date_val - min_year) / (max_year - min_year)) * 100) + 1
  paste0(colour_scale[idx], "FF")  # add full opacity
})
for (i in seq_along(polygons)) {
  plot(polygons[[i]], axes = FALSE, col = polygon_cols[i], add = TRUE, border = NA)
}

# Plot diffusion paths ------------------------------------------------------
for (i in seq_len(nrow(mcc_tab))) {
  curvedarrow(
    cbind(mcc_tab[i, "startLon"], mcc_tab[i, "startLat"]),
    cbind(mcc_tab[i, "endLon"],   mcc_tab[i, "endLat"]),
    arr.length = 0, arr.width = 0,
    lwd = 2, lty = 1, lcol = "gray20",
    arr.col = NA, arr.pos = FALSE,
    curve = 0.1, dr = NA, endhead = FALSE
  )
}

# Plot nodes ---------------------------------------------------------------
for (i in seq(nrow(mcc_tab), 1)) {
  # starting node
  if (i == 1) {
    points(mcc_tab[i, "startLon"], mcc_tab[i, "startLat"], pch = 16, col = colour_scale[1], cex = 0.8)
    points(mcc_tab[i, "startLon"], mcc_tab[i, "startLat"], pch = 1,  col = "gray20", cex = 0.8)
  }
  # end node
  points(mcc_tab[i, "endLon"], mcc_tab[i, "endLat"], pch = 16, col = end_year_colours[i], cex = 0.8)
  points(mcc_tab[i, "endLon"], mcc_tab[i, "endLat"], pch = 1,  col = "gray20", cex = 0.8)
}

# Axes & Legend -------------------------------------------------------------
rect(xmin(template_raster), ymin(template_raster), xmax(template_raster), ymax(template_raster), xpd = TRUE, lwd = 0.2)
axis(1, c(ceiling(xmin(template_raster)), floor(xmax(template_raster))), pos = ymin(template_raster),
     mgp = c(0,0.2,0), cex.axis = 0.5, lwd = 0, lwd.tick = 0.2, padj = -0.8, tck = -0.01, col.axis = "gray30")
axis(2, c(ceiling(ymin(template_raster)), floor(ymax(template_raster))), pos = xmin(template_raster),
     mgp = c(0,0.5,0), cex.axis = 0.5, lwd = 0, lwd.tick = 0.2, padj = 1,    tck = -0.01, col.axis = "gray30")

rast <- raster::raster(matrix(nrow = 1, ncol = 2))
rast[1] <- min_year; rast[2] <- max_year

plot(rast, legend.only = TRUE, add = TRUE, col = colour_scale, legend.width = 0.5, legend.shrink = 0.3,
     smallplot = c(0.40, 0.80, 0.14, 0.15), horizontal = TRUE,
     axis.args = list(at = seq(2000, 2025, 5), cex.axis = 0.6, lwd = 0, lwd.tick = 0.2,
                      tck = -0.5, col.axis = "gray30", line = 0, mgp = c(0, -0.02, 0)))

# Save figure ---------------------------------------------------------------
# ggsave("h7n9_continuous_spread_map.png", width = 10, height = 6.3, dpi = 600)

message("✔ Continuous diffusion map (H7N9) completed.") 